### ISSUE TITLE
Add support to use JSON files, instead of JSON

### ISSUE THREAD

**Issue by bbezerra82** [alexa/ask-cli#132]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ x ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

With v2 of the ASK CLI, there is no more support for the usage of JSON files and developers now need to use instead the contents of such files.
## Expected Behavior

When using <code>ask smapi create-isp-for-vendor</code> to create an ISP, for example, it would be great if I could just point to a JSON file, instead of having to paste the content of the file.
## Current Behavior
I need to past the entire content of the JSON file in the command line. 

## Possible Solution

Provide the feature again, such as it was in v1:
`$ ask api create-skill [-f|--file <fileName>] [-p|--profile <profile>] [--debug]`

## Your Environment and Context

* ask-cli version: 2.1.0
* Operating System and version: macOS 10.14.6
* Node.js version used for development: v13.7.0
* NPM version used for development:

**Comment by kakhaUrigashvili** [comment]
@bbezerra82 you can use 'cat' command to provide content of the file.

For example:

`ask smapi create-skill-for-vendor --manifest "$(cat skill-manifest.json)"`

Do you think we still need this feature?

**Comment by RonWang** [comment]
Hi @bbezerra82 , and I'd like to add based on @kakhaUrigashvili 's comment: it's because the v1's "--file" option doesn't support the case when users have a different way of file encoding (and some other fs configs), so if supporting that we still also support the configuration of fs.read basically. That's why the SMAPI command now supports the JSON string instead. For all the options that has a [JSON] tag in the --help, JSON string is expected. 

@kakhaUrigashvili  We might need to put this usage into our doc as well, and also including the Windows case where the replacement of `cat` is `type`.

**Comment by bbezerra82** [comment]
> @bbezerra82 you can use 'cat' command to provide content of the file.
> 
> For example:
> 
> `ask smapi create-skill-for-vendor --manifest "$(cat skill-manifest.json)"`
> 
> Do you think we still need this feature?

Hi @kakhaUrigashvili, I think this would be a nice bit of backwards compatibility, plus it give the developers the option. 
Out of curiosity, for other CLI tools, is the `cat`/`type` alternative the way they access the content of files or is the `--file` more common?

**Comment by kakhaUrigashvili** [comment]
@bbezerra82 Opened PR https://github.com/alexa/ask-cli/pull/151

**Comment by kakhaUrigashvili** [comment]
Added in 2.2.0
