### ISSUE TITLE
Bug report: ask -v not supported

### ISSUE THREAD

**Issue by bbezerra82** [alexa/ask-cli#138]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

`-v` is not a valid option to check for the ASK CLI version. `--version` or `-V` (capital V) work.
## Expected Behavior

For V1, `ask -v` was the short "single-dash" option to query the tool version. Is there a reason for this change? Is it somewhat related to a "verbose" option?
## Current Behavior

```
$ ask -v
error: unknown option '-v'
$ ask -V
2.1.1
$ ask --version
2.1.1
```
**CLI Snapshot**

## Steps to Reproduce (for bugs)

ASK-CLI V1:
```
$ ask -v
1.7.23
```
ASK-CLI V2
```
$ ask -v
error: unknown option '-v'
$ ask -V
2.1.1
$ ask --version
2.1.1
```
## Your Environment and Context

* ask-cli version: 2.1.1
* Operating System and version: macOS 10.14.6
* Node.js version used for development: v13.7.0
* NPM version used for development: 6.14.4

**Comment by RonWang** [comment]
@bbezerra82 Hi!

Yes `-V=--version` is used more frequently in the world of command line tools (e.g. `python -V`) and I think it's because -v need to be preserved as a possible alias for certain command. One very popular example is to use it as `-v=--verbose` option which can be useful for the ask-cli in the future. 

Thanks,
Ron

**Comment by bbezerra82** [comment]
Fair
