### ISSUE TITLE
Alexa-hosted skill as git submodule

### ISSUE THREAD

**Issue by higoorc** [alexa/ask-cli#142]
Hello guys, is there a way to add an Alexa-hosted skill as git submodule in another git repository? With the CLI we can do git push to deploy it, but If I try git submodule or git clone with the repository url which exists in git config always return 403.

I already tried to configure my AWS CLI to do that, but I can't see the CodeCommit resource in my account, so after authenticate instead 403 I receive 404, like the repository didn't exists.

Do you have any suggestion or maybe ideas to improve that with the CLI?

Thanks,

**Comment by RonWang** [comment]
Hey @higoorc ,

The Alexa-hosted skill provides the convenience for skill developers to skip the necessary skill backend setup work like AWS Lambda function creation (this is called skill infrastructure in v2 CLI). If I understand correctly you are trying to use AWS CLI to get the CodeCommit resource, which is actually owned by Alexa's AWS account and that's why you get 403 forbidden or 404 not exists in your account. For Alexa-hosted skill, you don't need to provide any AWS profile because the Alexa is provisioning the AWS account for your skill's backend.

If you are interested in how ask-cli manages the git repository, and how the CLI project has the permission to manage git, we use [git-credential-provider](https://git-scm.com/docs/gitcredentials) to give users permission of their git. You can also check this [code](https://github.com/alexa/ask-cli/blob/develop/lib/controllers/hosted-skill-controller/clone-flow.js#L66) to better get what ask-cli does for Alexa-hosted skill's project.

Thanks,
RonW

**Comment by RonWang** [comment]
Close the issue as I see the thumbs up emoji from the reported :) 
Feel free to reopen if you have further questions.
