### ISSUE TITLE
ask deploy -p profile_name (ask-cli v2)

### ISSUE THREAD

**Issue by fjaviermoradiaz** [alexa/ask-cli#156]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

ask deploy fail when try to deploy with a specific profile

## Expected Behavior

ask deploy -p profile_name should work fine.

## Current Behavior

ask deploy -p profile name doesn't work
Terminal show an error: **[Error]: CliError: Skill package src is not found in ask-resources.json.**

But if deploy using the same profile as default (ask deploy) it's work

**CLI Snapshot**
<img width="520" alt="Captura de pantalla 2020-05-01 a las 16 33 50" src="https://user-images.githubusercontent.com/19294854/80813078-9bfda480-8bc9-11ea-9a5a-6b3ed5729c52.png">

## Steps to Reproduce (for bugs)

 - Create an skill with ask-cli (v2)
 - Select java programming language
 - Select lambda backend

Compile with maven (mvn clean install)
 - ask deploy -p profile_name

## Your Environment and Context

* ask-cli version: 2.2.0
* Operating System and version: MacOS Mojave
* Node.js version used for development: v12.16.1
* NPM version used for development: 6.13.4

**Comment by kakhaUrigashvili** [comment]
@fjaviermoradiaz 
Looks like this error is explicitly thrown here
https://github.com/alexa/ask-cli/blob/develop/lib/commands/deploy/index.js#L88

It does seems like it is by design.

This is how I was able to solve it:
1) rm .ask/ask-states.json
2) add configuration section for the second profile in ask-resources.json
3) Possibly remove skill-package/skill.json manifest->api->custom->endpoint, since the name of the endpoint it dynamically constructed and has profile name in it.

**Comment by ChihYing7509** [comment]
@fjaviermoradiaz

The error message means CLI cannot find the skill-package under your profile. 
Please also make sure if you create the skill with your specific profile, using `ask new -p profile_name `.

**Comment by fjaviermoradiaz** [comment]
@ChihYing7509 this is the problem!!

I have created skill with ask new
and not set profile in this command :(

Thank u very much!!
