### ISSUE TITLE
revisionid updated even if lambda deploy fails and skill.json wasn't updated

### ISSUE THREAD

**Issue by AnjaMarxAmazon** [alexa/ask-cli#162]
[Error]: The current revisionId (The revision ID for Lambda ARN (arn:XXX) should be YYY, but found ZZZ. Please solve this revision mismatch and re-deploy again.

it is annoying that the revisionID is updated even if the deploy fails. Updating the revisionID introduces an extra step during bug fixing and deployment without any obvious added value.

**Comment by kakhaUrigashvili** [comment]
@AnjaMarxAmazon Would you mind providing details steps to reproduce?

I tested by removing lambda:UpdateFunctionCode from AWS user. The deploy failed but revisionId stayed the same in .ask/ask-states.json. 

Based on the code, the revisionId should not be updated if the lambda deploy fails.
https://github.com/alexa/ask-cli/blob/develop/lib/builtins/deploy-delegates/lambda-deployer/index.js#L82

I see the error is raised if revisionId .ask/ask-states.json does not match to revisionId of the deployed lambda
https://github.com/alexa/ask-cli/blob/develop/lib/builtins/deploy-delegates/lambda-deployer/helper.js#L42

**Comment by AnjaMarxAmazon** [comment]
Hello @kakhaUrigashvili it fails when removing lambda:UpdateFunctionConfiguration but updates the revisionID

**Comment by kakhaUrigashvili** [comment]
@AnjaMarxAmazon 
I was able to reproduce.
In case of failure due to UpdateFunctionConfiguration permission - lambda on AWS gets updated with new revisionId and .ask/ask-states.json still has the old revisionId.

Cause:
updateFunctionCode and updateFunctionConfiguration are non atomic operations

updateFunctionCode needs to to happen first and it generates revision id for updateFunctionConfiguration
https://github.com/alexa/ask-cli/blob/develop/lib/builtins/deploy-delegates/lambda-deployer/helper.js#L205

I think there are few solutions:
1) Make sure to have correct permissions - currently v2 already configures aws user with full lambda permissions. 
2) Update revision id after updateFunctionCode operation to be consistent with AWS.
3) Tried to make the operation atomic. I dont think it is possible to make it truly atomic on our side from technical standpoint. 

What do you think?


https://github.com/alexa/ask-cli/blob/develop/lib/builtins/deploy-delegates/lambda-deployer/helper.js#L213

**Comment by AnjaMarxAmazon** [comment]
I understand 1 and 2 are user-actions, with only 3 being a solution on the ask-cli side. I would vote for 3 because I think the revisionID shouldn't be updated in case of a failure - because there is nothing that (is supposed to) have changed. It is not clear what else a part from the revisionID has been updated even if the deploy failed, it may create doubt.

**Comment by RonWang** [comment]
Hey @AnjaMarxAmazon , first revisionId reflects both LambdaCode's change and LambdaConfiguration's change. To make it atomic, we can change to update revisionId whenever either of those two operation succeeds. For the current user who is facing this issue, erasing revisionId from ask-states.json would be the only solution. What do you think of this solution then? I can work on a PR for this solution to make sure the lambda-deployer doesn't miss any revisionId update.

**Comment by AnjaMarxAmazon** [comment]
Hi @RonWang yes, making both atomic sounds good to me. thanks.

**Comment by RonWang** [comment]
Hey @AnjaMarxAmazon , please use v2.9.0 which contains the fix of this issue. Your current config might already be corrupted, so need to get rid of the revisionId. But for your future usage, revisionId should not be orphaned anymore.
