### ISSUE TITLE
Project Structure for Using Same Code Backend for Multiple Skills

### ISSUE THREAD

**Issue by seanfisher** [alexa/ask-cli#164]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[x] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

I have six skills that ultimately each use the same backend code. With ask-cli v2, what is the recommended project/folder/manifest structure to manage these?

## More details:
The same code is deployed to six different lambdas (currently using Serverless framework). Each lambda, while using the same code, has different environment variables. The code uses the environment variables to adjust the behavior per-skill. Each skill's manifest points to the corresponding lambda function.

The code is in one Git repository. I would like to manage all six Alexa skill packages with the shared codebase. Something like the following project structure:

```
skills/
  skill1/
    skill.json
    interactionModels/
      custom/
        en-US.json
        // ...

  skill2/
    skill.json
    // ...

code/
  serverless.yml
  src/
  // ...
```

## Expected Behavior

I can manage the lambda deployment myself through Serverless and my CI/CD pipeline. But I'd like to be able to manage each skill package separately via the ask-cli. For example, accomplishing the two most fundamental tasks:
1. Deploying changes to the Alexa console: `ask deploy --package-path skills/skill1`
2. Downloading console changes to version control them. I believe the high-level functionality to do this was removed from the CLI (`ask clone` - I still don't understand why this was removed) and so this requires a collection of smapi commands: 
    `ask smapi get-skill-manifest --package-path skills/skill1 ...`
    `ask smapi get-interaction-model --package-path skills/skill1 ...`

## Current Behavior

Currently the suggested folder structure is clearly geared towards a 1-to-1 mapping between skill package and code. The top-level folder is called `skill-package` and holds just one skill definition.

## Possible Solution

Provide an optional parameter on the cli to specify the skill-package folder. For example,

    ask deploy --package-path skills/skill1

-or-
Update the documentation to suggest how a multi-skill, one-codebase solution could be managed. Something to do with profiles or ask-resources.json or something.

## Your Environment and Context

* ask-cli version: 2.0.0
* Operating System and version: any
* Node.js version used for development: any
* NPM version used for development: any

**Comment by RonWang** [comment]
Hey @seanfisher I believe the feature you requested can be achieved using the profile concept in CLI. If you can manage to set your ask-resources.json.profiles object to be something like
```
{
  "profile_1": {
    skillId: A,
    skillMetadata: {
      src: "skills/skill1"
    }
  },
  "profile_2": {
    skillId: B,
    skillMetadata: {
      src: "skills/skill2"
    }
  }
}
```
This assumes you have two profiles (preferred to be two different accounts though it can be totally same account) that stands for maybe two stages of your skill development. Then you can do `ask deploy profile_1/profile_2` to manage the target to deploy. Does this solves your question?

- Ron

**Comment by RonWang** [comment]
And in addition to some of your questions:
1. Removal of clone command. Please go to [here](https://github.com/alexa/ask-cli/blob/develop/docs/FAQ.md#q-since-v2-ask-cli-removes-ask-clone-command-what-should-i-do-to-download-my-skill-project) to check our explanation about the removal of v1 "ask clone" command, and its replacement flow. Basically you only need to do `ask smapi export-package` (instead of calling separate commands) and then use `ask init` to form the v2 project, and then you can deploy as normal.

2. Better instructions on how to manage multi-skill-package using profiles. I can think of a way to simplify your profile specific settings, which is through `ask init -p {profile1-6}` to go through a wizard to link six of your skill-package to the deploy config, separately. However, current init command doesn't have this functionality to add a profile into the deploy configuration file (i.e. ask-resources.json), it can only overwrite if file already exists. Do you think if we can add a profile into the deploy config file, it might make your experiences better?

**Comment by hideokamoto** [comment]
I think this request is a similar goal for my issue.
[Feature Request] Selectable Deployment S3 Bucket #174

We want to get an easy way to manage multiple skills by using ASK CLI(v2) with CloudForamtion/Serverless Framework.

**Comment by kakhaUrigashvili** [comment]
@seanfisher and @hideokamoto we have added ability to specify your own s3 bucket in version 2.18.0. I think you can achieve what you are looking for now.

https://github.com/alexa/ask-cli/blob/develop/docs/concepts/Alexa-Skill-Project-Definition.md#ask-resourcesjson-this-file-is-up-to-configure
