### ISSUE TITLE
Feature Request: ASK Dialog should return JSON or restore `--output` flag

### ISSUE THREAD

**Issue by btburton42** [alexa/ask-cli#173]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[X] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

End-to-end testing of Alexa is hampered by the ask dialog only outputting to `stdout`.

## Expected Behavior
Previously it was possible to write the output to a file using `--output`, but this feature has been removed. 

Current consumers of dialog simulation output have to parse and sanitize `stdout` text to assert against a set of expectations, which are more than likely already in JSON format.

Ideally, a simulation should be able to return a valid JSON object of the conversation. 

At minimum, the previous behavior of writing to a file would allow for better consumption of simulation output.

## Current Behavior
User must parse and sanitize std out using regex patterns like `/ \[22m\[39m/` to remove extra CLI output.

## Your Environment and Context

* ask-cli version: 2.5.1

**Comment by scvnc** [comment]
@btburton42 do you have a workaround snippet that sanitizes stdout? I'm curious for establishing rapid testing.

**Comment by kakhaUrigashvili** [comment]
@btburton42 and @scvnc what the the preferred format for the output file?

What is your primary use case? I am guessing you want to use it for some automated test.
For example
```
ask dialog --replay replay-file.json --output output-file.json
assert(output-file-content, expected-output-content)
```
Adding output flag is not very difficult, we just want to understand the use case so we can decide on the most appropriate format(text file, structured json, etc).

**Comment by scvnc** [comment]
Thanks for touching base @kakhaUrigashvili . I think what you describe captures the essence of what I'm trying to do. I think a text file is what I'm after which depicts the dialog being replayed between user and alexa. I'm coming at this fresh without having used ASK CLI v1 before. 

So far I've found it very useful, especially while developing branches of dialog and switching intents, to use the `--replay` switch to rapidly verify that the skill model and my deployed endpoint meets requirements as opposed to manually testing on an alexa device or console sim. I was going to see if I could capture the output on a series of replay files (as test scenarios) and then raise an error if the output differed in a meaningful way, then someone can manually review whether its a regression.

Since the CLI stdout is using some repl magic I don't quite understand, I've been unable to pipe the output to a file for a useful diff.  I tried installing v1 and the output file has a lot more information and I'm unsure if it could be quickly used for the use case I am describing.

### Aside: what I have explored from here

I have continued by looking at the [ask-smapi-sdk][0] and trying to build some tooling that would enable this and other e2e-like tests.  So far I've had some success. If other people land at this issue with similar desires, I will share some of my ideas for this tooling. I haven't concluded on an a desired api but it could be something like this:


```typescript
const alexaSim = new AlexaSimulator(/*smapi and skill config */)

let result = await alexaSim.utter("open travel agent and book a flight to Cancun")

expect(result.alexaSpeech).toEqual("Do you have a specific date in mind?");

result = await alexaSim.utter("no");

expect(result.alexaSpeech).toEqual("great, is there a particular month you have in mind");
```

Perhaps this would better enable one to use more sophisticated assertions and permutations, if desired.

I could potentially see some use similar to how [Bespoken][1] handles their tests with yaml that just superficially goes through a list of utterances and expected responses.  It would be much faster than trying to write mocha/jest tests and possibly allow non-devs to contribute to specs.  They charge ~$0.10 per utterance on their infrastructure and it seems like I'd bust the budget with the way I'd like to develop/test.

A friction point with this approach is that I lose the ease of configuration with the ASK cli.  `ask configure` is really nice.

[0]: https://github.com/alexa/alexa-skills-kit-sdk-for-nodejs/tree/2.0.x/ask-smapi-sdk
[1]: https://github.com/bespoken/bst

**Comment by btburton42** [comment]
@kakhaUrigashvili we would highly prefer structured JSON as that eliminates any cleanup on our end. Something similar to the "responseBody" that we get in the DEBUG - GET-SIMULATION method would be a a great start as that includes any metadata we send to the user such as cards or directives.

**Comment by scvnc** [comment]
Structured json would work for me. Perhaps an array of objects, one for each utterance/response and it could resemble what comes back from the smapi simulation endpoints. One could shallowly diff them or more easily hook into tooling which could parse/assert the request/responses. I noticed v1 had a bunch of human-readable delimiters between json objects involved in the output file, which is another friction point for machine parsing.

**Comment by kakhaUrigashvili** [comment]
@scvnc and @btburton42 I have opened a PR https://github.com/alexa/ask-cli/pull/252

Please let me know if you have any concerns about the output format.

**Comment by btburton42** [comment]
This looks great @kakhaUrigashvili!

**Comment by kakhaUrigashvili** [comment]
Added in version 2.12.0
example
`ask dialog --save-skill-io output.json`

**Comment by btburton42** [comment]
Looks great @kakhaUrigashvili! Can't wait to refactor the test runner.
