### ISSUE TITLE
Support for Cloudformation parameters

### ISSUE THREAD

**Issue by boardthatpowder** [alexa/ask-cli#211]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[X ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

It's not possible to use custom Cloudformation parameters which severely limits the effectiveness of being able to use Cloudformation as a deployment mechanism.

## Expected Behavior
If a user has the ability to define a Cloudformation template, they should have the ability to define and use parameters for said template.

## Current Behavior
No user defined parameters allowed.  Looking at the code, parameter injection is hardcoded.

## Steps to Reproduce (for bugs)
N/A

## Possible Solution
Allow users to define parameters as a map as `profiles.skillInfastructure.userConfig.templateParameters` within `ask-resources.json`.

## Your Environment and Context
* ask-cli version: 2.9.0

**Comment by conman124** [comment]
I've been annoyed at this recently too.  @kakhaUrigashvili I would like to make a PR with this feature, is there any specific process I need to follow?

**Comment by kakhaUrigashvili** [comment]
@conman124 Since most of the larger improvements requests are related to deployers,  I want to talk to the team about it. May be we can just a rewrite of cf deployer plus add new features. It is a little hard to add new new features now since it is all written with callbacks. Rewriting with more modern approaches using promises and async await would make much easier to maintain and contribute. 

Let me get back to you on it. I should be able to give you an answer by Wednesday the latest.

**Comment by kakhaUrigashvili** [comment]
@conman124 and @boardthatpowder opened PR https://github.com/alexa/ask-cli/pull/225

**Comment by RonWang** [comment]
Hey @boardthatpowder @conman124 ,

Thanks for your question and sorry for the wait. We had a discussion for your issue and try to deep dive into your needs for this support. One point that we might need both of your inputs is: can you configure those parameters directly in the Cloudformation template file, not in the ask-resources.json?

CLI's ask-resources.json is designed as the configuration file for your Alexa skill's deployment, especially for the skill's metadata (JSONs). The skill infrastructure part is fully up to the deployer: since by using AWS Cloudformation you will have the full control over your deployment of AWS infrastructures, `@ask-cli/cfn-deployer` is more like a pass-through deployer, and its userConfig field only tracks Alexa skill related fields (like the runtime and handler). For parameters other then those two, the skills' deployment doesn't really need to know. What are your thoughts over this? Does it make sense to your usage? Please kindly let us know.

Thanks,
Ron

**Comment by conman124** [comment]
@RonWang I would be ok dropping the support from ask-resources.json.  My main desire for putting it there is to enable "infrastructure as code" style deployments.  The other benefit is differing parameters based on the --profile passed to `ask deploy`.

However, requiring that the parameters be put in the CloudFormation template itself would sort of defeat the purpose of the parameters in the first place.  The need for this is to be able to change deployment parameters at deploy time (either through command line switches or the use of a specific profile)

If setting parameters won't be supported using @ask-cli/cfn-deployer, can you point me to (or write) documentation on creating a custom deployer?

**Comment by boardthatpowder** [comment]
Hey Ron.  

No that will not work.  It defeats the whole point of using CloudFormation.  Just like you may want to define account/region/environment specific configuration to inject into ask-resources.json, you may need to do the same with the CloudFormation template.  A simple example is needing to inject the name of an account specific bucket to pass to a lambda, or injecting the name of a specific Cognito user pool to integrate with.

Referencing the cloudformation template in ask-resources.json, but not providing parameters is a big disconnect.  If unwilling to modify ask-resources.json, can instead the ask cli be updated to pass parameters through (think --parameter-overrides arg) to the underlying cloudformation template?

**Comment by kakhaUrigashvili** [comment]
@conman124  and @boardthatpowder added in version 2.18.0 
https://github.com/alexa/ask-cli/blob/develop/docs/concepts/Alexa-Skill-Project-Definition.md#ask-resourcesjson-this-file-is-up-to-configure
