### ISSUE TITLE
[Feature request] MCS issue when Smarthome endpoint is Lambda and Custom endpoint is HTTPS

### ISSUE THREAD

**Issue by fredolphin** [alexa/ask-cli#215]
Hello,

I try to deploy a Multi Capacity Skill (Custom + Smart Home) using "ask deploy". The SmartHome component is calling a Lambda Function and the Custom component is calling my own backend.

The apis section is skill.json is:
    "apis": {
      "custom": {
        "endpoint": {
          "sslCertificateType": "Trusted",
          "uri": "https://api.domain.com"
        },
        "interfaces": []
      },
      "smartHome": {
        "endpoint": {
          "uri": "arn:aws:lambda:eu-west-1:xxxxx:function:FFFFFFFFR"
        },
        "protocolVersion": "3"
      }
    }

The Smart Home component is properly updated in the console. But not the Custom Part. The custom part endpoint is set with the SmartHome Lambda endpoint and not my own endpoint (i.e. https://api.domain.com).

Moreover, after the script execution, local skill.json is automatically updated. The endpoint for the custom part has as well being updated to the lambda arn.

Regards,
Frédéric

**Comment by RonWang** [comment]
Hey @fredolphin ,

Thanks for the report and sorry for waiting... ask-cli doesn't support MCS skill very much when the endpoints for different domains are not the same. When you execute the deploy command, CLI just updates endpoints (by region) for each existing skill types for the endpoint url. For now unfortunately, we could not deploy different AWS Lambda endpoints. We will consider this feature request and possibly let users control deployment target for each endpoint. Please stay tuned in this page.

Thanks,
Ron

**Comment by RonWang** [comment]
Hi @fredolphin we are working on the support for MCS skill, and we are referring to the example of MCS skill from https://github.com/alexa-labs/skill-sample-python-multi. 

Based on this template provided by our solution architects, it's pretty neat if one Lambda function is used to provision your functionality for both smarthome and custom domains. May I ask what's the reason that you need to use Https endpoint for your custom skill?

The reason why I asked this question is because we wish to understand better about your need and provide a very generic solution for users to configure multiple endpoints when needed. Right now our tool is working great when one Lambda per region is needed, either for lambda-deployer or cfn-deployer. We need to see your reason before we consider to expand that feature.

We might serve for the case when you only need one Lambda function. That said, we might also add a one-to-many mapping, to define what this endpoint will be used for. For example, you can set "SMARTHOME" in the deployer's userConfig, so that CLI won't overwrite for "CUSTOM".

Let us know your thoughts! We will try our best to make MCS DX better.

-Ron

**Comment by fredolphin** [comment]
Hi Ron,

Thank you for this update. 
My API endpoints are written in PHP and is used not only for Alexa but as well for Mobile Apps and other vocal assistants. It was developed before Alexa integration. That's why it is hosted on my own server. Redevelop all this API in a Lambda function (the API but as well the back-end logic with the database access and 3rd parties requests) is a huge job, I don't plan to do.

For the Smarthome Skill, I am using a Lambda only because it is mandatory and imposed by Amazon. But this lambda function is very simple and is only a path through to my PHP API.
For the Customer Skill, this pre-requisite is not imposed by Amazon. We can call directly a back-end in https without going through a Lambda function.  This behavior is kept even in the case of MSC skill.  Going through a lambda function could be indeed a solution (as I did for the Smarthome component). But, it will add latencies and it would be quite frustrating since it is not imposed by Alexa Console itself.

That's the reason, why I expect "ask" tool to support this configuration (Lambda endpoint for the smarthome component and https endpoint for the Custom component). 

Best Regards and thank you again for your investigation to make it better.
Frédéric

**Comment by RonWang** [comment]
Hi @fredolphin 

Thanks for your detailed answer, it's great to better understand our developers! To support your case, we decide to introduce a new field `targetEndpoint` into the ask-resources.json. We will still support the full management for one Lambda (per aws region). You will need to configure the `targetEndpoint` to decide what skill domains/capabilities you need for this Lambda endpoint.

Will let you know when it's released.
-Ron

**Comment by kakhaUrigashvili** [comment]
added targetEndpoint in version 2.21.0
