### ISSUE TITLE
Default `--stage` for SMAPI commands

### ISSUE THREAD

**Issue by habuma** [alexa/ask-cli#227]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[X] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Expected Behavior
Most/all of the `ask smapi` commands require the `--stage` or `-g` parameter. I'm guessing that *most* of the time the stage specified will be "development". Therefore, it would be helpful if the parameter defaulted to "development".

## Current Behavior
The `--stage`/`-g` parameter is required.

## Your Environment and Context
* ask-cli version: 2.10.1
* Operating System and version: MacOS 10.15.2
* Node.js version used for development: 12.16.2
* NPM version used for development: 6.14.4

**Comment by kakhaUrigashvili** [comment]
@habuma I have opened PR for your request. https://github.com/alexa/ask-cli/pull/244

I know you have a similar request for skill id, we are still thinking if we should implement it. Most of the smapi commands (120+) are autogenerated from swagger spec. All the help options are generated during the runtime. For stage we can show (default: "development") since it is deterministic. Skill id depends on profile and if the command is called from the project directory, so we cannot show what would be the default skill id deterministically. Additionally, since there are so many smapi commands we are trying to be cautious with adding any customization.

**Comment by kakhaUrigashvili** [comment]
@habuma default for stage is added in version 2.11.0
