### ISSUE TITLE
can't deploy my skills

### ISSUE THREAD

**Issue by baynado** [alexa/ask-cli#235]
i can't deploy my skills anymore. I've updsted my projects to cli v2 stricture. Then i used ask deploy for updating my skill. My foldersywer zipped andxthen it deploys and deploys for hours.

**Comment by baynado** [comment]
Now i could deploy my skill with code, but i get this error!!!!

{
    "errorType": "Runtime.ImportModuleError",
    "errorMessage": "Error: Cannot find module './dispatcher/error/mapper/GenericErrorMapper'\nRequire stack:\n- /var/task/node_modules/ask-sdk-runtime/dist/index.js\n- /var/task/node_modules/ask-sdk-core/dist/attributes/AttributesManagerFactory.js\n- /var/task/node_modules/ask-sdk-core/dist/index.js\n- /var/task/node_modules/ask-sdk/dist/skill/factory/StandardSkillFactory.js\n- /var/task/node_modules/ask-sdk/dist/index.js\n- /var/task/index.js\n- /var/runtime/UserFunction.js\n- /var/runtime/index.js",
    "stack": [
        "Runtime.ImportModuleError: Error: Cannot find module './dispatcher/error/mapper/GenericErrorMapper'",
        "Require stack:",
        "- /var/task/node_modules/ask-sdk-runtime/dist/index.js",
        "- /var/task/node_modules/ask-sdk-core/dist/attributes/AttributesManagerFactory.js",
        "- /var/task/node_modules/ask-sdk-core/dist/index.js",
        "- /var/task/node_modules/ask-sdk/dist/skill/factory/StandardSkillFactory.js",
        "- /var/task/node_modules/ask-sdk/dist/index.js",
        "- /var/task/index.js",
        "- /var/runtime/UserFunction.js",
        "- /var/runtime/index.js",
        "    at _loadUserApp (/var/runtime/UserFunction.js:100:13)",
        "    at Object.module.exports.load (/var/runtime/UserFunction.js:140:17)",
        "    at Object.<anonymous> (/var/runtime/index.js:43:30)",
        "    at Module._compile (internal/modules/cjs/loader.js:1133:30)",
        "    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)",
        "    at Module.load (internal/modules/cjs/loader.js:977:32)",
        "    at Function.Module._load (internal/modules/cjs/loader.js:877:14)",
        "    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)",
        "    at internal/main/run_main_module.js:18:47"
    ]
}

**Comment by kakhaUrigashvili** [comment]
@baynado Try the following solution:
https://github.com/alexa/ask-cli/blob/develop/docs/FAQ.md#q-for-windows-users-if-your-skill-return-empty-response-and-log-shows-module-not-found-genericerrormapper-or-cannot-find-module-dispatchererrormappergenericerrormapper-how-to-resolve

**Comment by ssenkus** [comment]
I am also having an issue deploying via `git push origin master`.

After upgrading my ask-cli to v2 and upgrading the project with `ask util upgrade-project`, I "cloned" the Skill locally using `ask init --hosted-skill-id SKILL_ID`.  The code structure has been verified to have the new structure.  I made a small change to a file in the master branch, then tried to push the commit.  

It just hangs...  

```
Pushing to https://git-codecommit.us-east-1.amazonaws.com/v1/repos/XXXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX
```

Is there anything else that I need to update?  I would like to publish my local changes so that my skill can be updated, but I am seriously blocked.  Any help is appreciated.

**Comment by kakhaUrigashvili** [comment]
@ssenkus I was not able to reproduce your issue. Are you on VPN? may be some kind if network issue?
Are you able to provide more details?
I dont even have this line in output when push succeeds.
```
git push origin master
After the code pushed, please check the deployment status
via Alexa Developer console:
https://developer.amazon.com/alexa/console/ask/build/custom/amzn1.ask.skill.00b9fb58-03d0-4cdf-94ce-316c3e532379/development/en_US
Enumerating objects: 7, done.
Counting objects: 100% (7/7), done.
Delta compression using up to 8 threads
Compressing objects: 100% (4/4), done.
Writing objects: 100% (4/4), 459 bytes | 459.00 KiB/s, done.
Total 4 (delta 1), reused 0 (delta 0)
To https://git-codecommit.us-east-1.amazonaws.com/v1/repos/00b9fb58-03d0-4cdf-94ce-316c3e532379
   4bd4654..43684c1  master -> master
```

**Comment by ssenkus** [comment]
@kakhaUrigashvili I run `git push origin master -v` and it hangs indefinitely.  If this is not an ASK CLI question, where should I go for help?

**Comment by kakhaUrigashvili** [comment]
@ssenkus so there is nothing special about your network?
what is your OS? what version is your node.js and git client?
You can try removing pre-push hooks
`mv .git/hooks/pre-push .git/hooks/pre-push-bck`

**Comment by ssenkus** [comment]
@kakhaUrigashvili Yes, `ask util git-credentials` gives me an encrypted username/password output.  

I tried moving the git pre-push hooks, no change.

I do not have any special network setup such as a VPN.  
OS: Mac OS Catalina 10.15.4
Node version:  v12.14.0
git version: 2.14.1

**Comment by kakhaUrigashvili** [comment]
@ssenkus  is it happening with only one skill? What happens if you create a new hosted skill with 'ask new' and try pushing it.

**Comment by ssenkus** [comment]
@kakhaUrigashvili I just found out I can push to the `dev` branch.  I wonder if there is some permissions issue...

I just created a new skill with `ask new` and am encountering the same issue.

**Comment by kakhaUrigashvili** [comment]
@ssenkus  you can try using 'ask smapi get-alexa-hosted-skill-user-permissions' to check permission.

**Comment by ssenkus** [comment]
@kakhaUrigashvili Ah, I figured it out!  

The file `ask-resources.json` was missing from the original repository that I had an issue with.  I found this by running `git push -vvv` for debug information.  The output and error (that was previously silent):
```
Pushing to https://git-codecommit.us-east-1.amazonaws.com/v1/repos/XXXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX
[Error]: CliFileNotFoundError: File /PATH/TO/MY_SKILL_REPO/ask-resources.json not exists.
```

I copied over the one that was generated from the test skill (`ask new`).

Thank you for your help, @kakhaUrigashvili.  I really appreciate it!

**Comment by kakhaUrigashvili** [comment]
@ssenkus I have noticed that ask-resources.json is in .gitignore file by default. I will need to investigate why was it designed this way. It may be the root cause of the issue.

**Comment by fboerncke** [comment]
Same problem here since some days ago. It used to work in the past but for some reason "git push" just freezes now as described above  ...

**Comment by kakhaUrigashvili** [comment]
@fboerncke can you help me to troubleshoot by checking the following:
1) Do you have ask-resources.json?
2) Do you have .ask/ask-states.json
3) Do you have something like this in .git/config file?
```
[credential "https://git-codecommit.us-east-1.amazonaws.com/v1/repos/<id>"]
	helper = 
	helper = !ask util git-credentials-helper --profile default
	UseHttpPath = true
```
4) Can you run `git push -vvv`  and see if there are any error messages?

**Comment by fboerncke** [comment]
@kakhaUrigashvili
I can confirm that the answer is "yes" to all three questions. 

Furthermore something has changed since yesterday: as of today "git push" does *not* hang anymore. I replayed my protocol from yesterday and git push does soemthing now and returns to the shell. 

However something is still weird: 

When configuring a new hosted skill from the Web Developer Console and I activate interactionModels for multiple languages not all of them are cloned to my system when running the first "ask init" for hosted skills. The other way round when I add a new locale within my development environment and run "git push" (after adding and comming them of course) then I won't find that new locale in my developer console after doing a refresh. 
 
Maybe I am not using things as expected? Regarding ask-cli v1 there is a nice article describing things here: https://developer.amazon.com/ja/blogs/alexa/post/8a602054-6ba8-4b6e-b298-c4811840e680/using-the-alexa-skills-kit-command-line-interface-with-alexa-hosted-skills

I had no problems using V1 in the past. But I understand that things have changed with V2. Is there a similar article available for ask-cli V2 regarding how you expect developers to use branches prod/master/dev?

**Comment by kakhaUrigashvili** [comment]
@fboerncke I did some testing. Here are my observations.

1) Change to lambda code. It worked for me both ways. I could change in web console and then git pull changes locally. I could change locally and do git push. Changes would be reflected in the web console with a small delay.
2) Change to skill manifest. Only worked one way. Changes with git push would reflect in the web console with small delay. Changes in the web console would not reflect when I did git pull.
3) Change to interaction model. Similar to point 2.

I also want to mention the following: master branch maps to development environment in the web console. prod maps to live.

v2 does not do anything special during git push or git pull. The issues that we see in point 2 and 3 is related to how it is implemented on the server side.

@RonWang did v1 has any special logic during git push/pull compare to v2?

**Comment by fboerncke** [comment]
Thanks for getting into this: 

Currently I have problems getting a skill certified because they tell me to change an invocation name which I did already for sure. Developer Console tells me my current model version is "17" while what I get when cloning the hosted skill via ask v2 is an older version of the file labelled version "10". This scenario somehow matches the case you listed under "2" when saying "Changes in the web console would not reflect when I did git pull".

What is not clear to me: is this a bug or is ask V2 not meant to be used this way? Is there some statement in the documentation saying "Don't touch the developer console anymore after you start using ask V2 on that skill"? This would be a serious statement.

**Comment by RonWang** [comment]
Hey @fboerncke ,

Recap of your issue: the source version control for hosted skill doesn't pick up the skill-package update from browser; but pushing the source code updates the skill-package. 

We will investigate if this behavior is expected or can be mitigated but still sorry for the inconvenience. The project deployment for Alexa-Hosted skill is mostly focused on the push-model now except the management of Lambda code. We will voice your experiences back to our service team. 

For now the best way to mitigate this issue would be two options:
1. If you have changed your skill-package from browser (i.e. skill.json, interactionModel, in-skill products), please use the relative API to downloaded them to local. Please run `ask smapi` to find the command, e.g. for interactionModel, you will want to call 
```
ask smapi get-interaction-model -s {skillId} -g {stage} -l {locale} > skill-package/interactionModel/custom/{locale}.json
```

2. If you need to inter-op between local and console, please use `ask init --hosted-skill-id {id}` command each time you modify the skill through web console, to re-init the project with the latest project source code.

Please also stay tuned in this thread for the solution~
Ron

**Comment by fboerncke** [comment]
Thanks for the update: I had problems with skill certifications as it turned out that testers saw a different invocation name than I saw in my browser. I ended up configuring a new skill from scratch and copying over all resources from one browser window (old skill) into the other new one and I had to do this locale by locale. For this task I avoided to make use of ask-cli V2 completely. 

I would accept when you say "_The project deployment for Alexa-Hosted skill is mostly focused on the push-model_". But if this is the intended behaviour then this should be made very clear within the documentation. This information could help other developers to save time - while I had to learn the hard way ...

Anyway: keep up the good work!
Frank
