### ISSUE TITLE
ASK cli commands(i.e. ask deploy --target skill) not working after upgrading to ask cli v2

### ISSUE THREAD

**Issue by ajaybhalerao1210** [alexa/ask-cli#249]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

ask deploy --target skill
Accepted values for `target` are: `all`, `lambda`, `skill`, and `model`. The default target is `all`, if not specified.

## Expected Behavior
We request to add a feature where only a part of skill should be upload. e.g. ask deploy --target skill should not only deploy skill  
## Current Behavior
Now, ask deploy is deploying both skill and lambda.

**CLI Snapshot**

## Steps to Reproduce (for bugs)
ask deploy

## Possible Solution

Now, ask deploy command should only deploy part of skill.

## Your Environment and Context

* ask-cli version: 2.10.2
* Operating System and version:
* Node.js version used for development:  v12.14.0
* NPM version used for development: v 6.13.4

**Comment by cisnky** [comment]
This is being worked on https://github.com/alexa/ask-cli/pull/232

I do like your parameter options; all, lambda, skill, and model

**Comment by RonWang** [comment]
Hey @cisnky ,

In v1 CLI, supporting a granular target like `skill` `model` or `lambda` makes sense since it calls the exact APIs to update each resource; however in v2 CLI it relies on the skill package service which contain all the alexa JSON files. The { skill, model, isp } targets in v1 are all represented within the skill-package. By relying on the service, each call is able to smartly only deploy whatever is changed and make sure your deployment time minimum. That's why we could only set the v2's target as skill-metadata and skill-infrastructure which stands for the Alexa's JSONs and the skill's (AWS) backend.

Does this work for you?
Ron

**Comment by cisnky** [comment]
Hi @RonWang 

This makes sense, thanks for the update.

Ant

**Comment by kakhaUrigashvili** [comment]
Added in version 2.12.0
