### ISSUE TITLE
Cannot use -p or --profile on "ask util generate-lwa-tokens"

### ISSUE THREAD

**Issue by DanMittendorf** [alexa/ask-cli#294]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[x] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Expected Behavior

I'm trying to generate-lwa-tokens but want to use a profile using "ask util". The documentation states that this is possible: https://developer.amazon.com/en-US/docs/alexa/smapi/ask-cli-command-reference.html#generate-lwa-tokens

But running "ask util generate-lwa-tokens --profile XYZ" with an existing profile results in an error "unknown option '--profile'"

## Steps to Reproduce (for bugs)

> ask --version 
> 2.15.0
> ask util generate-lwa-tokens --profile xyz
> error: unknown option '--profile'
> ask util generate-lwa-tokens -p xyz
> error: unknown option '-p'

## Possible Solution

Either update the docs if it's not possible to use --profile or even better would be to implement support for --profile

## Your Environment and Context

* ask-cli version: 2.15.0
* Operating System and version: Windows 10, running ask-cli in WSL
* Node.js version used for development: 12.18.3
* NPM version used for development: 6.14.6

**Comment by kakhaUrigashvili** [comment]
@DanMittendorf thank you for the feature request. there is no relationship between profile and generating lwa tokens.

In order to generate lwa token ask cli uses client-id and client-confirmation. The client-id and client-confirmation allow to generate access and refresh tokens. Profile is pair of access and refresh tokens. Ask cli uses the same  client-id and client-confirmation to generate all profiles. With `ask util generate-lwa-token` you can either generate new access and refresh token with client-id and client-confirmation that is used by ask cli itself or provide your own client-id and client-confirmation.

https://developer.amazon.com/docs/dash/lwa-web-api.html#obtain-refresh-and-access-tokens-using-authorization-code-grant

**Comment by DanMittendorf** [comment]
Got it. Makes sense. Please make sure to update the documentation accordingly please so that others don't try/use this. ;-) Thanks.

**Comment by shanedroid** [comment]
I just hit this today as well using [v2.16.0](https://github.com/alexa/ask-cli/releases/tag/v2.16.0) , sunk some time into checking all my local things and ended up here. 

The docs for `ask cli` are still not updated to refkect that using `--profile | -p <profile>` is not possible

**Comment by kakhaUrigashvili** [comment]
@shanedroid I have created an internal ticket for documentation team to update the page. We also keep our documentation here https://github.com/alexa/ask-cli/tree/develop/docs/concepts. Feel free to contribute and add docs for util commands.
