### ISSUE TITLE
Cannot change Lambda ARN

### ISSUE THREAD

**Issue by paul-uz** [alexa/ask-cli#336]
I am using Ask v2.20.0 and I am trying to change the Lambda ARN defined in `skill.json`

I created the project first with `ask init` and a fresh Lambda Function was created, but I want to hook the skill up to an existing Function.

So I changed the ARN in `skill.json` and used `ask deploy` but the ARN was changed back.

I tried changing the endpoint in the Alexa web console, and saved, and tried deploying (via CLI) again, but the JOSN config still reverted back to the fresh Function ARN.

Is it possibly to change the ARN, at all? Or am I stuck using the one that is created when I create the skill?

**Comment by kakhaUrigashvili** [comment]
@paul-uz You can set
userConfig -> sourceLambda- > arn in ask-resources.json to use your own lambda arn

More details: https://github.com/alexa/ask-cli/blob/develop/docs/concepts/Deploy-Command.md

**Comment by paul-uz** [comment]
@kakhaUrigashvili this is my ask-resource.json file

```
{
  "askcliResourcesVersion": "2020-03-31",
  "profiles": {
    "default": {
      "skillMetadata": {
        "src": "./skill-package"
      },
      "code": {
        "default": {
          "src": "./lambda"
        }
      },
      "skillInfrastructure": {
        "userConfig": {
          "runtime": "nodejs12.x",
          "handler": "index.handler",
          "awsRegion": "eu-west-1"
        },
        "type": "@ask-cli/lambda-deployer"
      }
    }
  }
}
```

No `userConfig` section

**Comment by kakhaUrigashvili** [comment]
You need to change it to something like this

```
{
   "askcliResourcesVersion":"2020-03-31",
   "profiles":{
      "default":{
         "skillMetadata":{
            "src":"./skill-package"
         },
         "code":{
            "default":{
               "src":"./lambda"
            }
         },
         "skillInfrastructure":{
            "userConfig":{
               "runtime":"nodejs12.x",
               "handler":"index.handler",
               "awsRegion":"eu-west-1",
               "sourceLambda":{
                  "arn":"arn:aws:lambda:us-east-1:200074948102:function:test"
               }
            },
            "type":"@ask-cli/lambda-deployer"
         }
      }
   }
}
```

**Comment by paulcanning** [comment]
I'll give that a try.

I'm trying to setup a skill fully via CLI, but I think there is a circular dependency.

Let's so I start and make an empty lambda function. I need to add the Alexa trigger, but you need to add a Skill ID.

I cannot get a skill ID until a skill is created, but to create a skill via CLI from nothing, you have to deploy, which will make its own empty lambda function...

Seems like a lot of redundancy, and that you cannot create a skill from nothing, tied to an existing lambda function, via CLI.

**Comment by kakhaUrigashvili** [comment]
@paulcanning you can create skill from scratch by just running a couple of commands.

```
ask new # select lambda deployer
cd created-skill-folder
ask deploy
```
It will create new lambda and skill in correct order.
Later if you want to use your own lambda, you need to set userConfig -> sourceLambda- > arn in ask-resources.json and make sure the lambda provided already created and has Alexa trigger enabled.

At this moment, the ask cli would not create lambda with custom arn (userConfig -> sourceLambda- > arn) if the lambda does not exists. 

There is no option to provide arn when lambda is created.
https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Lambda.html#createFunction-property

I think what you are asking is custom name for the lambda instead of autogenerated name by the ask cli. Is there a reason auto generated name does not work for you?

**Comment by paulcanning** [comment]
Yes, the auto generated name is undesirable, and cannot be renamed.

Our lambda functions following naming conventions that we'd like to keep.

How is the auto generated name created? Is there a way I can name my skill in a way to get a better auto generated name?

**Comment by kakhaUrigashvili** [comment]
@paulcanning https://github.com/alexa/ask-cli/blob/develop/lib/clients/aws-client/lambda-client.js#L33

**Comment by paul-uz** [comment]
@kakhaUrigashvili it would be much more beneficial to allow the setting of a custom ARN name

**Comment by paul-uz** [comment]
@kakhaUrigashvili I tried the following:

* created skill project with auto generated lambda function
* create new lambda function, with custom name, added Alexa skill trigger with alexa skill ID
* changed config to point to custom ARN
* deployed no issue

I then deleted the `.ask` folder (assuming it should not be in version control, so simulating a new developer setting up the project) and then tried to deploy, but got the following error:

`The trigger setting for the Lambda arn:aws:lambda:eu-west-1:123456789000:function:AlexaTest is invalid.`

**Comment by kakhaUrigashvili** [comment]
@paul-uz 

1) I agree it would be more beneficial to allow the setting of a custom ARN name or possibly creating lambda if sourceLambda -> arn is specified.  I will talk to the team about adding it.
2) Yes. You need to have .ask/ask-states.json in source control. ask cli will created new skill if you dont have this file(it has skill id).  There is also lambda arn in skill-package/skill.json under manifest ->apis -> custom. If you deleted .ask folder, you also need delete endpoint under manifest ->apis -> custom. I know it is confusing, but this is how it was designed and changing it would be a breaking change.

@paulcanning  and @paul-uz have you tried using CloudFormation deployer? I think you can accomplish having custom Lambda name. You can pass extra parameters to CFN deployer in ask-resources.json. You can use the parameter infrastructure/cfn-deployer/skill-stack.yaml. I would encourage to use CFN deployer instead of Lambda deployer since it is more customizable.

**ask-resources.json**
```
{
  "askcliResourcesVersion": "2020-03-31",
  "profiles": {
    "default": {
      "skillMetadata": {
        "src": "./skill-package"
      },
      "code": {
        "default": {
          "src": "./lambda"
        }
      },
      "skillInfrastructure": {
        "userConfig": {
          "runtime": "nodejs10.x",
          "handler": "index.handler",
          "templatePath": "./infrastructure/cfn-deployer/skill-stack.yaml",
          "awsRegion": "us-east-1",
          "cfn": {
            "parameters": {
              "LambdaName": "my-custom-name"
            }
          }
        },
        "type": "@ask-cli/cfn-deployer"
      }
    }
  }
}
```

**infrastructure/cfn-deployer/skill-stack.yaml**

```
AWSTemplateFormatVersion: 2010-09-09
Parameters:
...
  LambdaName:
    Type: String
Resources:
...
  AlexaSkillFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Ref LambdaName
     ....
```

**Comment by paul-uz** [comment]
@kakhaUrigashvili you stated that `.ask` should be in version control, but here, https://github.com/alexa/ask-cli/issues/286#issuecomment-676765476, you states `.ask` should be in `.gitignore` - which is it?

**Comment by kakhaUrigashvili** [comment]
@paul-uz .ask/ask-states.json has skill-id if you dont put .ask/ask-states.json in the version control the cli will try to create new skill every time. My other comment was about hosted skill, which behaves differently.
To clone hosted skill, a developer needs to run 'ask init --hosted-skill-id <hosted-skill-id>', which will clone hosted skill repo and set up git credential helper. To deploy hosted skill, a developer needs to run "git add., git commit, git push" vs "ask deploy".

**Comment by RonWang** [comment]
Hey @paul-uz , I also think you should try cfn-deployer for your case. I believe you can configure everything AWS Lambda service supports using the stack using the example above. 

For the version control (not including Alexa hosted skill, as we have the workflow ready for our users - from version control to auto-deployment), I think ask-states.json should not be included most of the case. You may have question why we have two files: ask-resources and ask-states. The answer is the first one is for user configurable data, and the second is supposed to be read-only. The ask-states.json is where we track the IDs for remote resources, as well as temporary data. That's why it's not supposed to be SVC'ed.

If you wish to work with a teammate or across machines, I suggest you first git-clone the source code, then run `ask init` command to setup the deployment target - the skill-id. And set userConfig.sourceLambda.arn to the same Lambda ARN. Will this flow solve your need?

**Comment by paul-uz** [comment]
@kakhaUrigashvili I am wanting to publish code to an existing skill.

I ran `ask init` and entered the skill ID. It then asks for the `skill package path` but this does not exist yet on my machine (i thought `ask init` should have made this?) The same goes for `lambda code path` - you cannot enter a non-existant folder, but I havent written any code yet....

So, if i make an empty `skill package path` folder and empty `lambda code path` folder, I end up with `ask-resources.json` and `.ask/ask-states.json`

I want to set the skill ID, but doing so in `ask-states.json` won't work (as we established previously) - it needs to be in `skill.json` - which doesnt exist for me.

My question is simple - how do I use the ASK CLI to create an empty skill project where I can drop in my code, and set the Lambda ARN and Skill ID to my own values (and in exactly which files I need to do that)?

**Comment by paul-uz** [comment]
Also @kakhaUrigashvili you stated to require `ask-states.json` in SVN, but @RonWang is advising against?

Again, why are multiple files required for configuration?

Why can the Lambda ARN and Skill ID not be set in the same place?

**Comment by paul-uz** [comment]
@kakhaUrigashvili in your reply about CloudFormation deployer, 

```
"cfn": {
            "parameters": {
              "LambdaName": "my-custom-name"
            }
          }
```

Is `my-custom-name` the Lambda ARN? If not, what is it?

**Comment by kakhaUrigashvili** [comment]
@paul-uz try the following steps

1) 
```
mkdir existing-skill; cd existing-skill
mkdir lambda
cp -r ../alexa-sample-node/lambda/ lambda/ # or any other way to copy lambda code
ask smapi export-package -s amzn1.ask.skill.286da05f-3ae9-4729-9b0f-f98f2f40a080 -g development
ask init
? Skill Id (leave empty to create one):  amzn1.ask.skill.286da05f-3ae9-4729-9b0f-f98f2f40a080
? Skill package path:  ./skill-package
? Lambda code path for default region (leave empty to not deploy Lambda):  ./lambda
? Use AWS CloudFormation to deploy Lambda?  No
? Lambda runtime:  nodejs10.x
? Lambda handler:  index.handler
```


2) modify ask-resources.json and indicate sourceLambda since you want to reuse existing lambda.

This only work for Lambda deployer - for CF deployer need to modify CF template to accept Lambda Arn and add this parameter to ask-resources.json

https://github.com/alexa/ask-cli/blob/develop/docs/concepts/Deploy-Command.md
https://github.com/alexa/ask-cli/blob/develop/docs/concepts/Deployer-CFN-Deployer.md

```
.....
"skillInfrastructure": {
        "type": "@ask-cli/lambda-deployer",
        "userConfig": {
          "runtime": "nodejs10.x",
          "handler": "index.handler",
          "awsRegion": "us-east-1",
          "sourceLambda": {
            "arn": "arn:aws:lambda:us-east-1:200074948102:function:ask-node-skill-default-default-1608223548393"
          }
        }
}
```

3) 
```
ask deploy
.....
==================== Deploy Skill Infrastructure ====================
  ✔ Deploy Alexa skill infrastructure for region "default"
Skill infrastructures deployed successfully through @ask-cli/lambda-deployer.

==================== Enable Skill ====================
Skill is already enabled, skip the enable process.
```

**Comment by paulcanning** [comment]
I am only using the cloud formation system deployer.

In your reply, you mention CF, but then show json config which references lambda deployer.

I tried CF deployer, and as I said, if lamdab function was created prior, it doesn't work. You have to let the CF deployer make the function, but I don't want that.

**Comment by kakhaUrigashvili** [comment]
@paulcanning please see this reply https://github.com/alexa/ask-cli/issues/364#issuecomment-747620223
it may help. This is how the Cloud Formation works, there is no function arn property:
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lambda-function.html

**Comment by paul-uz** [comment]
@kakhaUrigashvili I am now trying to change the Lambda ARN in the config files to something entirely new and deploy it, but i get 

```
"message": "The trigger setting for the Lambda arn:aws:lambda:eu-west-1:<account_id>:function:<new_arn> is invalid."
```

I set the new ARN in `ask-resource.json`

```
"skillInfrastructure": {
        "type": "@ask-cli/cfn-deployer",
        "userConfig": {
          "runtime": "nodejs12.x",
          "handler": "index.handler",
          "templatePath": "./infrastructure/cfn-deployer/skill-stack.yaml",
          "awsRegion": "eu-west-1",
          "cfn": {
            "parameters": {
              "LambdaName": "arn:aws:lambda:eu-west-1:<account_id>:function:<new_arn>"
            }
          }
        }
      }
```

And also set the API endpoint in `skill.json`.

Why isn't the Cloudformation Deployer creating a new Lambda Function for me?

**Comment by kakhaUrigashvili** [comment]
@paul-uz 

1) LambdaName should be just name not ARN. CFN does not support LambdaArn: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lambda-function.html
2) You need to modify infrastructure/cfn-deployer/skill-stack.yaml to pass the custom parameter 'LambdaName'

for example
```
AWSTemplateFormatVersion: 2010-09-09
Parameters:
  LambdaName: ## add this
    Type: String 
  SkillId:
    Type: String
...........
Resources:
  ......
  AlexaSkillFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: !Ref CodeBucket
        S3Key: !Ref CodeKey
        S3ObjectVersion: !Ref CodeVersion
      Handler: !Ref LambdaHandler
      Runtime: !Ref LambdaRuntime
      Role: !GetAtt AlexaSkillIAMRole.Arn
      FunctionName: !Ref LambdaName ## add this
.....
```

**Comment by jsetton** [comment]
@kakhaUrigashvili @RonWang The solution you provided above to setup a custom Lambda function name doesn't work when deploying to all regions. The CFN deployer shouldn't create two separate stacks in the default region in that specific case. I have opened #388.
