### ISSUE TITLE
Get "ResourceConflictException" after opt-in AWS lambda states update 

### ISSUE THREAD

**Issue by rayandben2000** [alexa/ask-cli#415]
## I'm submitting a...

<pre><code>
[x] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request 
[ ] Other... Please describe: 
</code></pre>

## Expected Behavior

It should deploy lambda successfully when I opt-in AWS lambda states update.

## Current Behavior

I follow the [Coming soon: Expansion of AWS Lambda states to all functions](https://aws.amazon.com/de/blogs/compute/coming-soon-expansion-of-aws-lambda-states-to-all-functions/) to add `aws:states:opt-in` in function’s description. Running ask deploy will failed and get error message:
```
[Error]: CliError: The lambda deploy failed for Alexa region "default": ResourceConflictException: The operation cannot be performed at this time. An update is in progress for resource: arn:aws:lambda:${my function id}
```
If I remove `aws:states:opt-in` in function’s description, it can deploy normally.

## Your Environment and Context

* ask-cli version:  2.24.1
* Operating System and version:
* Node.js version used for development: v15.12.0
* Yarn version used for development: 1.21.1

**Comment by Xyon75** [comment]
I'm having this issue since this morning deploying in the eu-west-1 region.
Is there any way to fix this before Dec 6th?

**Comment by tmsoft** [comment]
Set the function to "aws:states:opt-out" to deploy again.

**Comment by mhaddy** [comment]
Any update here?

**Comment by arctouch-pedrocosta** [comment]
Any updates? I'm also experiencing the same problem as other engineers here. My workflow will be blocked as of 12/6 and this is the main SDK to deploy Alexa Skills with lambda functions.

**Comment by sam-goodwin** [comment]
Looks like it's a problem with how we use revision id when updating lambda function. Tracing that code:

CLI will load the Lambda Function information from AWS and store it in `deployState`

https://github.com/alexa/ask-cli/blob/b6fb7b95a42fcdf00c3003a70ba8742c7fd8ebb5/lib/builtins/deploy-delegates/lambda-deployer/index.js#L62

Then, when updating the Lambda, the `revisionId` is extracted from that object:

https://github.com/alexa/ask-cli/blob/b6fb7b95a42fcdf00c3003a70ba8742c7fd8ebb5/lib/builtins/deploy-delegates/lambda-deployer/helper.js#L241

And then uses it when updating the Function:
https://github.com/alexa/ask-cli/blob/b6fb7b95a42fcdf00c3003a70ba8742c7fd8ebb5/lib/builtins/deploy-delegates/lambda-deployer/helper.js#L241-L250

It calls UpdateFunctionConfiguration afterwards but it uses the latest RevisionId:
https://github.com/alexa/ask-cli/blob/b6fb7b95a42fcdf00c3003a70ba8742c7fd8ebb5/lib/builtins/deploy-delegates/lambda-deployer/helper.js#L249

From the conversation here, this seems to be related to AWS Lambda States. Reading the docs: https://docs.aws.amazon.com/lambda/latest/dg/functions-states.html

>The following operations fail while function creation is pending:
> * Invoke
> * UpdateFunctionCode
> * UpdateFunctionConfiguration
> * PublishVersion

I think the fix is to wait until the state changes before calling UpdateFunctionConfiguration.

**Comment by sam-goodwin** [comment]
Hey all, sorry for the delay on this. I've put together a PR for what I think should fix this issue. Still need to test but would also like some feedback on the desired behavior: https://github.com/alexa/ask-cli/pull/422

**Comment by sam-goodwin** [comment]
I will test this once I get back in to the office. Until then, feel free to check out #422 and run the following commands to install it as your CLI

```
npm install
npm run prepublishOnly
npm pack
npm install -g ./ask-cli-2.24.1.tgz
```

**Comment by arctouch-pedrocosta** [comment]
Hi @sam-goodwin, thank you for the update on this issue, I will be watching your PR, based on the latest comments sounds like I should wait to update to the newer version, will keep an eye out.

**Comment by jsetton** [comment]
If anyone want to test the PR I submitted above, you can install it using the command below:

```
npm install -g jsetton/ask-cli#lambda-state-update-fix
```

**Comment by arctouch-pedrocosta** [comment]
Hi @jsetton my tests were successful with your branch, I was able to deploy latest code changes to my lambda function code to AWS without issues. It's looking good on my end. My understanding is that your code still have to finish going through review before a new release can be rolled out correct?

**Comment by arctouch-pedrocosta** [comment]
Really appreciate your work so far @jsetton !

**Comment by jsetton** [comment]
> My understanding is that your code still have to finish going through review before a new release can be rolled out correct?

This is correct but you can use the version I submitted in the meantime. Since ask-cli checks for the latest available official release each time you run the tool, you will be notified when to switch back to the official one.
