### ISSUE TITLE
How to get lambda function name of alexa hosted skill

### ISSUE THREAD

**Issue by Nikhil-Wagh** [alexa/ask-cli#76]
## I'm submitting a 

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Expected Behavior
A list of lambda functions under that account

## Current Behavior
Currently, there is no way to get a list of lambda functions under my account. If there is I couldn't find it [here](https://developer.amazon.com/en-US/docs/alexa/smapi/ask-cli-command-reference.html#lambda-command).
I should be able to do `ask lambda --list` or `ask lambda -l`

## Possible Solution
Add an option `-l` to `ask lambda` subcommand that will give a list of lambda functions with their arn(s).

## Your Environment and Context

* ask-cli version: 1.7.23
* Operating System and version: macOS Catalina 10.15.2 (19C57)
* Node.js version used for development: v10.16.0
* NPM version used for development: 6.14.2
* Python version: Python 3.8.2
* pip version: pip 20.0.2

**Comment by nikhilym** [comment]
Hey @Nikhil-Wagh , aws cli already helps you with [that] (https://docs.aws.amazon.com/lambda/latest/dg/gettingstarted-awscli.html#with-userapp-walkthrough-custom-events-list-functions). Isn't this sufficient?

**Comment by Nikhil-Wagh** [comment]
Yes, that is helpful. Thanks.

**Comment by nikhilym** [comment]
> Yes, that is helpful. Thanks.

You are welcome. :-)

> But the only thing is I have to install another application when I already have the `ask cli`, can it not do the job, it already does other things like uploading and downloading the code.

It can. But it would need to jump through a lot of hoops to get that information, which is not ideal. Since skill code is user specific, and there are different ways of hosting the skill (lambda, https endpoint, alexa hosted), it might not be ideal for ASK CLI to do the job of figuring out your AWS Lambda functions. 

Maybe if you are only looking for a skill specific lambda arn (or even skill specific endpoint info), then that information can already be retrieved from `get-skill-manifest` API call I guess.

**Comment by nikhilym** [comment]
Btw the issue title and description are two different things. So let us know which one you are actually looking out for

**Comment by RonWang** [comment]
Since this thread is not active we will close it for now.

And in addition @Nikhil-Wagh , since Alexa hosted skill's Lambda function is not owned under your account, the function name will not be super useful for you as you cannot configure it using AWS APIs. For non-Hosted skill, you can try to use aws-cli as @nikhilym mentioned above.
