### ISSUE TITLE
Provide a -f parameter to force the creation of resources (overwrite existing or recreate missing ones)

### ISSUE THREAD

**Issue by germanviscuso** [alexa/ask-cli#77]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

Provide a `askx deploy -f` where mismatches in hashes are ignored and resources are recreated where necessary. Similar to the -f option in the original ASK-CLI.

## Expected Behavior

For example if I delete my lambda function via AWS and the do askx deploy -f my lambda function is regenerated without complaints.

## Current Behavior

The -f option doesn't exist

**CLI Snapshot**

## Your Environment and Context

* ask-cli version: x.x.x
* Operating System and version:
* Node.js version used for development:
* NPM version used for development:

**Comment by RonWang** [comment]
Hey @germanviscuso 

Thanks for this request! As you may notice, we are trying to abstract all the skill components with a delegated platform. `skillMetadata` is backed by Alexa Skill Package service; `skillInfrastructure` is back by a growing deployer platform such as Alexa-Hosted skill service, or AWS Cloudformation, or lightweight flexible lambda-deployer. The definition of "**--force**" is still not super clear to us, as different platform has their different resource management logics.

In CLI v1, we can use force because CLI is the engine that calls different APIs, we can use force to bypass some exception. However, with the growth of our dependent upstream, adding a force concept no longer fits as they are smart enough to decide if it's force-able, and further provides the support of it through the API. 

For example to your case, if you delete a Lambda outside CloudFormation, it should just fail as the flow is intervened, the state of that resource is not 100% guaranteed to be identical as before if you want to create it back by CFN. 

If you can think of other cases that you need a force flag, please let us know! We will evaluate and think what is the best that we can do.

Thanks,
Ron

**Comment by willblaschko** [comment]
I use force all the time when I make small changes in the dev dashboard GUI to test how certain functionality would work before going back and making permanent changes to my version-controlled skill (either small tweaks or full JSON copy). Especially true when designing my language model.

I also use force when updating my Lambda settings (memory/CPU), as it's super quick to set there.

I've found this workflow faster than alternatives, even if potentially not best practice. Are these use cases correctly supported using the new CLI without force?

**Comment by RonWang** [comment]
Hi @willblaschko ~ the --force option is introduced in v1 when we start to support eTag for each resource (like skill manifest or IModel etc.), the force deploy is used to ignore those eTag checks. But now in CLI v2, we don't use eTag but only the reliance on skill-package platform. That's why in v2 CLI the project deploy will still go through, if you already have some changes in the console.

I was curious how do you update Lambda configurations using --force in v1, because it doesn't support the update of Lambda memory/CPU in v1. That said, it is supported in v2 now, with lambda-deployer if you set [userConfig](https://github.com/alexa/ask-cli/blob/develop/docs/concepts/Deploy-Command.md#ask-clilambda-deployer) in ask-resources.json, or with cfn-deployer's cloudformation stack where you can configure anything you need for AWS Lambda function.

Overall, we wish we can help developers do the resources management smartly but if it cannot cover all the user scenarios, we will definitely consider extend our features. We need more user voices to make the decision.

Thanks,
Ron

**Comment by RonWang** [comment]
Close this issue because of the inactivity in this thread, please feel free to reopen the issue if you need further help!

**Comment by Mistic92** [comment]
Is there any plan to implement -f? Somehow when I do ask util upgrade-project and then ```ask deploy``` all the time I'm getting warning that hash has not changed. I want to force deploy of alexa skill.

```
==================== Deploy Skill Metadata ====================
[Warn]: The hash of current skill package folder does not change compared to the last deploy hash result, CLI will skip the deploy of skill package.
Skill ID: XXXXXXXXX
==================== Build Skill Code ====================
Skill code built successfully.

```

**Comment by RonWang** [comment]
Hey @Mistic92 ,

Could you tell me why you need to force the deploy? Based on the message, it seems the hash comparison tries to help you skip unnecessary skill-package deployment, as there is no new changes committed to the local skill-package folder. Is it not correct?

**Comment by Mistic92** [comment]
Hi, when it's building on cicd it doesn't know about previous push so it's generating current&previous hash when it's doing ```ask util upgrade-project```. Because of that, ```deploy``` is thinking that it's the latest version.

**Comment by RonWang** [comment]
Hey @Mistic92 ! Sorry is it okay for you to elaborate why you need to use upgrade-project command in your CICD? Because the command is not designed be used in CICD in our opinion, and we thought it should be used only once for each skill project... Maybe with more details over your usage, we can understand better and propose a better solution! And a continuous integration is also based on a relative stable project right? But upgrade-project is not the command that provides a static project...

**Comment by Mistic92** [comment]
Hi, we started using Jovo for developing for alexa but it's not compatible with ask 2.x so we need to use upgrade-project each time when it generate alexa files, unfortunately. I was thinking that it won't be the problem to do it each time until Jovo will be upgraded but I'll try to find other way. Maybe I'll clear hash field with another script as it's allowing deploy with empty hash field.

**Comment by Anand-lab** [comment]
Hi @RonWang , 

I have few skill in my account which I published using v1 but now when I upgraded my old projects using upgrade-project and then try to deploy I always get  this warning "The hash of current skill package folder does not change compared to the last deploy hash result, CLI will skip the deploy of skill package." and it doesn't deploy lambda changes.

It would be useful if we provided with --force option which will deploy whole project again inspite of hash value.

**Comment by kakhaUrigashvili** [comment]
PR is open https://github.com/alexa/ask-cli/pull/163

**Comment by kakhaUrigashvili** [comment]
Added --ignore-hash option to deploy command in version 2.5.0.
