### ISSUE TITLE
Do not overwrite uri in skill.json after deployment

### ISSUE THREAD

**Issue by germanviscuso** [alexa/ask-cli#81]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

It's nice that you're going in the direction of encapsulating all deployment specific parameters inside the `.ask` directory (I saw that the lambda code with dependencies now goes there too). However there's something that breaks this which is that the lambda deployment uri is overwritten with the full uri path on `skill.json` after deploy. If you take a look at all the skill samples that we offer in github.com/alexa in `skill.json` we only specify the `sourceDir` (eg lambda) and the short function name as `uri` (eg. skill-demo-xxx) and the CLI v1 accepts it and can work with it (the arn is taken from `.ask/config` and the CLI v1 does not overwrite the `uri` in `skill.json`).
This not only nice because it does not polute a skill specs file that if often under version control but also has the nice side effect of allowing un to just pass the function name that we want to use in the lambda function (the old CLI takes a short uri name as the name of the function when deploying)

## Current Behavior

**CLI Snapshot**

## Your Environment and Context

* ask-cli version: 0.11.0
* Operating System and version:
* Node.js version used for development:
* NPM version used for development:

**Comment by RonWang** [comment]
Hey @germanviscuso ,

Thanks for your reasoning! I just have one thing that need to correct about one of your comments: 
> it does not polute a skill specs file

In CLI v1, it does somehow pollute the skill manifest defined by upstream (SMAPI). With the CLI's modification to skill.json, it becomes not inter-operable when you want to use it in any other places. That's why we move those CLI addition to ask-resources.json and .ask/ folder.

Also, passing in the Lambda function name can be convenient but the logical leap/gap also exists. Strange things might happen, like when you expect new Lambda will be created by CLI, but it turns out it's updating a Lambda function that just conflicts with the name. 

In terms of this update behavior, because the creation of AWS Lambda needs skill-id as the input (it's the recommended method), CLI's current flow is to first create skill-id, then deploy Lambda, then register Lambda ARN back to skill and update again.

The skill template from Github will work for v1, but with v2's project structure, we believe it will be a long term advantage to skill developers, as CLI clarifies its usage as a configurable deployment tool. The new project structure provides a much more transparent flow to users as for what can be controlled and what is CLI's data.

Hope you will enjoy it!
Ron
